# Site settings
title: MattarLab
email: your-email@domain.com
url: https://example.github.io
description: "Our research lab studies the evolutionary and cultural origins of human behavior. We study a broad range of topics related to social behavior in the laboratory and in the field, using economic games, physiological measurements, ethnographic interviews, and surveys."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#D3D3D3'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
